# Generated by Django 6.0.3 on 2026-03-23 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=255)),
                ('preparacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('apellidos', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nto', models.DateField(blank=True, null=True)),
                ('poblacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tlf_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('tutor_fct', models.CharField(blank=True, max_length=255, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ciclo')),
            ],
        ),
    ]
