# Generated by Django 6.0.3 on 2026-05-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cif', models.CharField(max_length=20, unique=True)),
                ('representante', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('tutor_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_convenio', models.DateField(blank=True, null=True)),
                ('plazas', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_centro', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('horas', models.IntegerField(default=400)),
                ('horas_comp', models.IntegerField(default=0)),
                ('obs', models.TextField(blank=True, null=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.alumno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
    ]
