# Generated by Django 5.0.6 on 2026-05-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_empresa_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ano',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.CharField(blank=True, choices=[('GS', 'Grado Superior'), ('GM', 'Grado Medio'), ('B', 'Básica'), ('FPB', 'FP Básica')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='num_alumno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='turno',
            field=models.CharField(blank=True, choices=[('M', 'Mañana'), ('T', 'Tarde'), ('O', 'Online')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.ciclo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
