# Generated by Django 5.0.6 on 2026-05-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alumno_ano_alumno_curso_alumno_email_alumno_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cif',
            field=models.CharField(max_length=20),
        ),
    ]
